# Generated by Django 5.1.6 on 2025-02-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Welcome!", max_length=255)),
                ("subtitle", models.TextField(blank=True, default="Its description.")),
                ("about_me", models.TextField(blank=True, default="Im very good.")),
                (
                    "contact_email",
                    models.EmailField(default="support@localhost", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+38 (063) 000-00-00", max_length=20),
                ),
            ],
        ),
    ]
