# Generated by Django 5.1.6 on 2025-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_mainpagesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpagesettings",
            name="contact_phone",
            field=models.CharField(
                blank=True, default="+38 (063) 000-00-00", max_length=20
            ),
        ),
    ]
