# Generated by Django 5.1.6 on 2025-02-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_mainpagesettings_contact_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainpagesettings",
            name="contact_phone",
        ),
        migrations.AddField(
            model_name="mainpagesettings",
            name="contact_github",
            field=models.CharField(
                blank=True, default="https://github.com", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="mainpagesettings",
            name="contact_linkedin",
            field=models.CharField(
                blank=True, default="https://linkedin.com", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="mainpagesettings",
            name="contact_telegram",
            field=models.CharField(blank=True, default="https://t.me", max_length=255),
        ),
        migrations.AlterField(
            model_name="mainpagesettings",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="support@localhost", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="mainpagesettings",
            name="subtitle",
            field=models.TextField(default="Its description."),
        ),
    ]
