# Generated by Django 5.1.6 on 2025-02-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_project_end_date_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="rating",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
