# Generated by Django 5.1.6 on 2025-02-19 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_project_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPageProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MainPageProjectOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.project"
                    ),
                ),
                (
                    "main_page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.mainpageprojects",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
