# Generated by Django 5.1.6 on 2025-02-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_mainpageprojects_mainpageprojectorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpageprojects",
            name="projects",
            field=models.ManyToManyField(
                through="crm.MainPageProjectOrder", to="crm.project"
            ),
        ),
        migrations.AlterField(
            model_name="mainpageprojectorder",
            name="main_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.mainpageprojects"
            ),
        ),
    ]
