# Generated by Django 5.1.6 on 2025-02-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_mainpageprojects_projects_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="rating",
            new_name="rating_difficulty",
        ),
        migrations.AddField(
            model_name="project",
            name="rating_overall",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="project",
            name="rating_usefulness",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
