# Generated by Django 5.1.6 on 2025-02-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_tag_color"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
